name: Build & Push ndc-cassandra
on: workflow_dispatch

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) This repo (so we can read the Dockerfile you added)
      - name: Checkout this repo
        uses: actions/checkout@v4

      # 2) Upstream source goes into ./upstream
      - name: Checkout upstream source
        uses: actions/checkout@v4
        with:
          repository: hasura/ndc-cassandra
          ref: main
          path: upstream
          fetch-depth: 0

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}   # e.g. orbgio
          password: ${{ secrets.DOCKERHUB_TOKEN }}      # Docker Hub PAT (Write)

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .                                  # repo root containing ./upstream
          file: .github/docker/ndc-cassandra.Dockerfile
          platforms: linux/amd64
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/ndc-cassandra:dev-latest
          cache-from: type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/ndc-cassandra:buildcache
          cache-to: type=registry,ref=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/ndc-cassandra:buildcache,mode=max
